# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      AUTO_COMMITTER_EMAIL: ${{ github.event.repository.owner.email }}
      AUTO_COMMITTER_NAME: CI Service
      BUILD_BRANCH: build-${{ github.sha }}
      GENERATE_DIR: ./docs
      PREFIX: /${{ github.event.repository.name }}

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: GENERATE_DIR=./docs PREFIX=/nuxt2-static yarn generate
    - name: Setup Git profile
      run: |
        git config user.email $AUTO_COMMITTER_EMAIL
        git config user.name $AUTO_COMMITTER_NAME
    - name: Push pages to origin/main
      run: |
        git add ./pages
        git commit -m "Update pages"
        git push origin main
    - name: Switch to build branch
      run: |
        git branch $BUILD_BRANCH main
        git checkout $BUILD_BRANCH
    - name: Push docs to origin/pages
      run: |
        git add ./docs
        git commit -m "Update docs"
        git push origin $BUILD_BRANCH:pages -f
